# Generated by Django 5.2 on 2025-04-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCrew',
            fields=[
                ('crewid', models.AutoField(db_column='CrewID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('dob', models.DateField(db_column='DOB')),
                ('nationality', models.CharField(db_column='Nationality', max_length=50)),
            ],
            options={
                'db_table': 'FilmCrew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminMovieManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AdminMovieManagement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('adminid', models.AutoField(db_column='AdminID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BelongsTo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genrename', models.CharField(db_column='GenreName', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.IntegerField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('releaseyear', models.CharField(db_column='ReleaseYear', max_length=4)),
                ('duration', models.IntegerField(db_column='Duration')),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_column='Role', max_length=8)),
            ],
            options={
                'db_table': 'PartOf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ReviewModeration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('reviewdate', models.DateField(db_column='ReviewDate')),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StreamingPlatforms',
            fields=[
                ('platformname', models.CharField(db_column='PlatformName', max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='URL', max_length=255)),
            ],
            options={
                'db_table': 'StreamingPlatforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('crewid', models.OneToOneField(db_column='CrewID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cinegatorapp.filmcrew')),
            ],
            options={
                'db_table': 'Actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('crewid', models.OneToOneField(db_column='CrewID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cinegatorapp.filmcrew')),
            ],
            options={
                'db_table': 'Directors',
                'managed': False,
            },
        ),
    ]
